version: '3.1'

services:

  saas-admin:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    image: 'saas-admin'
    ports:
      - 80:80
    volumes:
       - ./src/admin:/var/www/html

  database:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - .docker/db/init.sh:/docker-entrypoint-initdb.d/init.sh

  database-client:
    image: adminer
    restart: always
    environment:
      ADMINER_DEFAULT_DB_DRIVER: pgsql
      ADMINER_DEFAULT_DB_HOST: database
      ADMINER_DESIGN: haeckel
      ADMINER_PLUGINS: tables-filter tinymce
    ports:
      - 54320:8080
  mailhog:
    image: mailhog/mailhog:latest
    restart: always
    ports:
      - 1025:1025
      - 8025:8025    